NAVIGATION_CATALOG = (
    {
        'topic_keys': (
            'заказы поставщикам',
            'заказы на покупку',
            'purchase order',
            'po',
        ),
        'label': 'Заказы поставщикам',
        'action_xml_id': 'purchase.purchase_form_action',
        'context_defaults': {'search_default_my_purchases': 1},
        'required_groups': ('purchase.group_purchase_user',),
        'menu_breadcrumb': 'Закупки -> Заказы',
    },
    {
        'topic_keys': (
            'запросы коммерческих предложений',
            'зкп',
            'rfq',
            'закупки',
        ),
        'label': 'Запросы коммерческих предложений',
        'action_xml_id': 'purchase.purchase_rfq',
        'required_groups': ('purchase.group_purchase_user',),
        'menu_breadcrumb': 'Закупки -> Заказы -> Запросы КП',
    },
    {
        'topic_keys': (
            'поставщики',
            'vendors',
            'supplier',
            'контрагенты поставщики',
        ),
        'label': 'Поставщики',
        'action_xml_id': 'account.res_partner_action_supplier',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Закупки -> Заказы -> Поставщики',
    },
    {
        'topic_keys': (
            'требования прорабов',
            'требования на комплектацию',
            'object request',
            'or',
        ),
        'label': 'Требования на комплектацию',
        'action_xml_id': 'object_request.action_object_request',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Требования -> Требования на комплектацию',
    },
    {
        'topic_keys': (
            'объекты',
            'проекты объектов',
            'object request projects',
        ),
        'label': 'Объекты',
        'action_xml_id': 'object_request.action_object_request_project',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Требования -> Объекты',
    },
    {
        'topic_keys': ('аналитика требований', 'статистика требований'),
        'label': 'Аналитика требований',
        'action_xml_id': 'object_request.action_object_request_analytics',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Требования -> Аналитика',
    },
    {
        'topic_keys': ('приемки', 'приёмки', 'receipts', 'поступления'),
        'label': 'Поступления',
        'action_xml_id': 'stock.action_picking_tree_incoming',
        'required_groups': ('stock.group_stock_user',),
        'menu_breadcrumb': 'Склад -> Операции -> Поступления',
    },
    {
        'topic_keys': (
            'внутренние перемещения',
            'internal transfers',
            'внутренние переводы',
        ),
        'label': 'Внутренние перемещения',
        'action_xml_id': 'stock.action_picking_tree_internal',
        'required_groups': ('stock.group_stock_user',),
        'menu_breadcrumb': 'Склад -> Операции -> Внутренние перемещения',
    },
    {
        'topic_keys': ('трансферы', 'операции склада', 'stock transfers'),
        'label': 'Трансферы',
        'action_xml_id': 'stock.action_picking_tree_all',
        'required_groups': ('stock.group_stock_user',),
        'menu_breadcrumb': 'Склад -> Операции -> Трансферы',
    },
    {
        'topic_keys': (
            'остатки',
            'наличие',
            'stock report',
            'остатки товаров',
        ),
        'label': 'Остатки товаров',
        'action_xml_id': 'stock.action_product_stock_view',
        'required_groups': ('stock.group_stock_user',),
        'menu_breadcrumb': 'Склад -> Отчетность -> Наличие',
    },
    {
        'topic_keys': ('места хранения', 'локации', 'locations'),
        'label': 'Места хранения',
        'action_xml_id': 'stock.action_location_form',
        'required_groups': ('stock.group_stock_user',),
        'menu_breadcrumb': 'Склад -> Конфигурация -> Места хранения',
    },
    {
        'topic_keys': (
            'инвентаризация',
            'physical inventory',
            'inventory adjustment',
        ),
        'label': 'Физическая инвентаризация',
        'action_xml_id': 'stock.action_stock_inventory_adjustement_name',
        'required_groups': ('stock.group_stock_user',),
        'menu_breadcrumb': 'Склад -> Операции -> Физическая инвентаризация',
    },
    {
        'topic_keys': ('товары', 'номенклатура', 'products'),
        'label': 'Товары',
        'action_xml_id': 'product.product_template_action',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Склад -> Товары -> Товары',
    },
    {
        'topic_keys': ('контакты', 'contacts', 'партнеры'),
        'label': 'Контакты',
        'action_xml_id': 'contacts.action_contacts',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Контакты',
    },
    {
        'topic_keys': ('мои настройки', 'мой профиль', 'preferences'),
        'label': 'Мои настройки',
        'action_xml_id': 'base.action_res_users_my',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Пользователь -> Мои настройки',
    },
    {
        'topic_keys': ('crm воронка', 'воронка продаж', 'pipeline'),
        'label': 'Воронка CRM',
        'action_xml_id': 'crm.crm_lead_action_pipeline',
        'required_groups': ('sales_team.group_sale_salesman',),
        'menu_breadcrumb': 'CRM -> Продажи -> Воронка',
    },
    {
        'topic_keys': ('лиды', 'crm leads', 'лиды crm'),
        'label': 'Лиды',
        'action_xml_id': 'crm.crm_lead_all_leads',
        'required_groups': ('sales_team.group_sale_salesman',),
        'menu_breadcrumb': 'CRM -> Лиды',
    },
    {
        'topic_keys': ('коммерческие предложения', 'quotations', 'кп продажи'),
        'label': 'Коммерческие предложения',
        'action_xml_id': 'sale.action_quotations_with_onboarding',
        'required_groups': ('sales_team.group_sale_salesman',),
        'menu_breadcrumb': 'Продажи -> Заказы -> Коммерческие предложения',
    },
    {
        'topic_keys': ('заказы на продажу', 'sales orders', 'продажи заказы'),
        'label': 'Заказы на продажу',
        'action_xml_id': 'sale.action_orders',
        'required_groups': ('sales_team.group_sale_salesman',),
        'menu_breadcrumb': 'Продажи -> Заказы -> Заказы',
    },
    {
        'topic_keys': ('аудит ai', 'ai audit', 'лог ai', 'журнал ai'),
        'label': 'Аудит AI Assistant',
        'action_xml_id': 'ai_assistant.action_ai_assistant_audit',
        'required_groups': ('ai_assistant.group_ai_assistant_admin',),
        'menu_breadcrumb': 'Настройки -> AI Assistant -> Audit',
    },
    {
        'topic_keys': ('чат ai', 'ai assistant', 'чат ассистента'),
        'label': 'AI Assistant',
        'path': 'ai-assistant',
        'required_groups': ('ai_assistant.group_ai_assistant_user',),
        'menu_breadcrumb': 'Панель Odoo -> AI Assistant',
    },
    {
        'topic_keys': ('dashboard', 'главная', 'панель приложений'),
        'label': 'Главная панель Odoo',
        'path': 'apps',
        'required_groups': ('base.group_user',),
        'menu_breadcrumb': 'Главная панель Odoo',
    },
)
